name: 'Containers'
description: 'Builds and optionally pushes container images'

inputs:
  container-registry-server:
    description: 'Container registry server'
    default: 'docker.io'
    required: false
  container-registry-username:
    description: 'Container registry username'
    required: false
  container-registry-password:
    description: 'Container registry password'
    required: false
  wemogy-packages-token:
    description: 'The token to use to authenticate with the wemogy-packages service'
    required: true
  version:
    description: 'The version of the container image'
    required: true
  push:
    description: 'Whether to push the container image to the registry'
    required: true
    default: 'false'
  dockerfile-path:
    description: 'Path to Dockerfile'
    required: false
    default: '.'
  context-path:
    description: 'Build context path'
    required: false
    default: '.'
  image-name:
    description: 'Name of the Docker image'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Login to Azure Container Registry
      if: inputs.push == 'true'
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.container-registry-server }}
        username: ${{ inputs.container-registry-username }}
        password: ${{ inputs.container-registry-password }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      if: inputs.push == 'true'
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context-path }}
        file: ${{ inputs.dockerfile-path }}/Dockerfile
        push: true
        tags: ${{ inputs.container-registry-server }}/${{ inputs.image-name }}:${{ inputs.version }}
        build-args: |
          WEMOGY_PACKAGES_TOKEN=${{ inputs.wemogy-packages-token }}

    - name: Build Docker image (no push)
      if: inputs.push == 'false'
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context-path }}
        file: ${{ inputs.dockerfile-path }}/Dockerfile
        push: false
        tags: ${{ inputs.image-name }}:${{ inputs.version }}
        build-args: |
          WEMOGY_PACKAGES_TOKEN=${{ inputs.wemogy-packages-token }}
