/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthUiRouteImport } from './routes/auth-ui'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Tenant2RegisterRouteImport } from './routes/tenant2/register'
import { Route as Tenant2LoginRouteImport } from './routes/tenant2/login'
import { Route as Tenant1RegisterRouteImport } from './routes/tenant1/register'
import { Route as Tenant1LoginRouteImport } from './routes/tenant1/login'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUiRoute = AuthUiRouteImport.update({
  id: '/auth-ui',
  path: '/auth-ui',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Tenant2RegisterRoute = Tenant2RegisterRouteImport.update({
  id: '/tenant2/register',
  path: '/tenant2/register',
  getParentRoute: () => rootRouteImport,
} as any)
const Tenant2LoginRoute = Tenant2LoginRouteImport.update({
  id: '/tenant2/login',
  path: '/tenant2/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Tenant1RegisterRoute = Tenant1RegisterRouteImport.update({
  id: '/tenant1/register',
  path: '/tenant1/register',
  getParentRoute: () => rootRouteImport,
} as any)
const Tenant1LoginRoute = Tenant1LoginRouteImport.update({
  id: '/tenant1/login',
  path: '/tenant1/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth-ui': typeof AuthUiRoute
  '/login': typeof LoginRoute
  '/tenant1/login': typeof Tenant1LoginRoute
  '/tenant1/register': typeof Tenant1RegisterRoute
  '/tenant2/login': typeof Tenant2LoginRoute
  '/tenant2/register': typeof Tenant2RegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-ui': typeof AuthUiRoute
  '/login': typeof LoginRoute
  '/tenant1/login': typeof Tenant1LoginRoute
  '/tenant1/register': typeof Tenant1RegisterRoute
  '/tenant2/login': typeof Tenant2LoginRoute
  '/tenant2/register': typeof Tenant2RegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth-ui': typeof AuthUiRoute
  '/login': typeof LoginRoute
  '/tenant1/login': typeof Tenant1LoginRoute
  '/tenant1/register': typeof Tenant1RegisterRoute
  '/tenant2/login': typeof Tenant2LoginRoute
  '/tenant2/register': typeof Tenant2RegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth-ui'
    | '/login'
    | '/tenant1/login'
    | '/tenant1/register'
    | '/tenant2/login'
    | '/tenant2/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-ui'
    | '/login'
    | '/tenant1/login'
    | '/tenant1/register'
    | '/tenant2/login'
    | '/tenant2/register'
  id:
    | '__root__'
    | '/'
    | '/auth-ui'
    | '/login'
    | '/tenant1/login'
    | '/tenant1/register'
    | '/tenant2/login'
    | '/tenant2/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthUiRoute: typeof AuthUiRoute
  LoginRoute: typeof LoginRoute
  Tenant1LoginRoute: typeof Tenant1LoginRoute
  Tenant1RegisterRoute: typeof Tenant1RegisterRoute
  Tenant2LoginRoute: typeof Tenant2LoginRoute
  Tenant2RegisterRoute: typeof Tenant2RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-ui': {
      id: '/auth-ui'
      path: '/auth-ui'
      fullPath: '/auth-ui'
      preLoaderRoute: typeof AuthUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant2/register': {
      id: '/tenant2/register'
      path: '/tenant2/register'
      fullPath: '/tenant2/register'
      preLoaderRoute: typeof Tenant2RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant2/login': {
      id: '/tenant2/login'
      path: '/tenant2/login'
      fullPath: '/tenant2/login'
      preLoaderRoute: typeof Tenant2LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant1/register': {
      id: '/tenant1/register'
      path: '/tenant1/register'
      fullPath: '/tenant1/register'
      preLoaderRoute: typeof Tenant1RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant1/login': {
      id: '/tenant1/login'
      path: '/tenant1/login'
      fullPath: '/tenant1/login'
      preLoaderRoute: typeof Tenant1LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthUiRoute: AuthUiRoute,
  LoginRoute: LoginRoute,
  Tenant1LoginRoute: Tenant1LoginRoute,
  Tenant1RegisterRoute: Tenant1RegisterRoute,
  Tenant2LoginRoute: Tenant2LoginRoute,
  Tenant2RegisterRoute: Tenant2RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
