name: Release NPM package
on:
  push:
    branches:
      - release

jobs:
  get-version:
    name: Get release version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      next-version: ${{ steps.get-release-version.outputs.version }}
      next-version-name: ${{ steps.get-release-version.outputs.version-name }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: wemogy/get-release-version-action@v4.3.2
        id: get-release-version
        with:
          mode: semantic
          create-tag: true
          prefix: v
          git-username: wemogy IT
          git-email: it@wemogy.com

  release:
    name: Release NPM package
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    needs:
      - get-version
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: ./.github/actions/setup-node
        with:
          packages-token: ${{ secrets.WEMOGY_PACKAGES_TOKEN }}

      - name: Update package version
        run: pnpm -r exec pnpm version ${{ needs.get-version.outputs.next-version }} --no-git-tag-version --allow-same-version

      - name: Build library
        run: pnpm build

      - name: Publish NPM package
        run: pnpm publish -r --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.get-version.outputs.next-version-name }}
          name: Version ${{ needs.get-version.outputs.next-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    needs:
      - get-version
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Build and push idp-backend to Azure Container Registry
        uses: ./.github/actions/containers
        with:
          container-registry-server: ${{ secrets.AZURE_CONTAINER_REGISTRY_SERVER }}
          container-registry-username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
          wemogy-packages-token: ${{ secrets.WEMOGY_PACKAGES_TOKEN }}
          version: ${{ needs.get-version.outputs.next-version }}
          push: true
          dockerfile-path: 'apps/idp-backend'
          context-path: '.'
          image-name: 'better-auth-cosmos/idp-backend'
